/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test/in" instead.
 */

#include <check.h>
#include <stdio.h>

#include "../decimal/bitwise_helper.h"
#include "../decimal/s21_decimal.h"

START_TEST(set_sign_positive) {
  s21_decimal value = {0};
  set_sign(&value, plus);

  ck_assert(((value.bits[3] >> 31) & 1) == plus);
}
END_TEST

START_TEST(set_sign_negative) {
  s21_decimal value = {0};
  set_sign(&value, minus);

  ck_assert(((value.bits[3] >> 31) & 1) == minus);
}
END_TEST

START_TEST(get_sign_positive) {
  s21_decimal value = {0};
  set_sign(&value, plus);

  ck_assert(get_sign(value) == plus);
}
END_TEST

START_TEST(get_sign_negative) {
  s21_decimal value = {0};
  set_sign(&value, minus);

  ck_assert(get_sign(value) == minus);
}
END_TEST

START_TEST(set_bit_zero_false) {
  s21_decimal value = (s21_decimal){{0}};
  set_bit(&value, 0, false);

  ck_assert(get_bit(value, 0) == false);
}
END_TEST

START_TEST(set_bit_zero_true) {
  s21_decimal value = (s21_decimal){{0}};
  set_bit(&value, 0, true);

  ck_assert(get_bit(value, 0) == true);
}
END_TEST

START_TEST(set_bit_one_false) {
  s21_decimal value = (s21_decimal){{1}};
  set_bit(&value, 0, false);

  ck_assert(get_bit(value, 0) == false);
}
END_TEST

START_TEST(set_bit_one_true) {
  s21_decimal value = (s21_decimal){{1}};
  set_bit(&value, 16, true);

  ck_assert(get_bit(value, 16) == true);
}
END_TEST

START_TEST(set_bit_middle_false) {
  s21_decimal value = (s21_decimal){{0}};
  set_bit(&value, 16, false);

  ck_assert(get_bit(value, 16) == false);
}
END_TEST

START_TEST(set_bit_middle_true) {
  s21_decimal value = (s21_decimal){{0}};
  set_bit(&value, 16, true);

  ck_assert(get_bit(value, 16) == true);
}
END_TEST

START_TEST(set_bit_overflow_true) {
  s21_decimal value = (s21_decimal){{0}};
  set_bit(&value, 96, true);

  ck_assert(get_bit(value, 96) == true);
}
END_TEST

START_TEST(set_bit_overflow_false) {
  s21_decimal value = (s21_decimal){{0}};
  set_bit(&value, 96, false);

  ck_assert(get_bit(value, 96) == false);
}
END_TEST

START_TEST(add_positive_numbers) {
  s21_decimal value_1 = {{10, 0, 0, 0}};
  s21_decimal value_2 = {{20, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{30, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_negative_numbers) {
  s21_decimal value_1 = {{10, 0, 0, 0}};
  s21_decimal value_2 = {{20, 0, 0, 0}};
  set_sign(&value_1, minus);
  set_sign(&value_2, minus);
  s21_decimal expected = {{30, 0, 0, 0x80000000}};
  s21_decimal result = {{0, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_positive_numbers_float) {
  s21_decimal value_1 = {{10, 0, 0, 0}};
  s21_decimal value_2 = {{20, 0, 0, 0}};
  set_scale(&value_1, 10);
  set_scale(&value_2, 5);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{1000032, 0, 0, 0}};
  set_scale(&expected, 5);
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_negative_numbers_float) {
  s21_decimal value_1 = {{10, 0, 0, 0}};
  s21_decimal value_2 = {{20, 0, 0, 0}};
  set_sign(&value_1, minus);
  set_sign(&value_2, minus);
  set_scale(&value_1, 10);
  set_scale(&value_2, 5);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{1000032, 0, 0, 0x80000000}};
  set_scale(&expected, 5);
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_positive_numbers_float_int) {
  s21_decimal value_1 = {{10, 0, 0, 0}};
  s21_decimal value_2 = {{20, 0, 0, 0}};
  set_scale(&value_1, 10);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{100000000020, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_negative_float_positive_int) {
  s21_decimal value_1 = {{10, 0, 0, 0}};
  s21_decimal value_2 = {{20, 0, 0, 0}};
  set_sign(&value_1, minus);
  set_scale(&value_1, 10);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{99999999980, 0, 0, 0x80000000}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_positive_int_negative_float) {
  s21_decimal value_1 = {{10, 0, 0, 0}};
  s21_decimal value_2 = {{20, 0, 0, 0}};
  set_sign(&value_2, minus);
  set_scale(&value_2, 5);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{1999990, 0, 0, 0x80000000}};
  set_scale(&expected, 5);
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_negative_int_positive_float) {
  s21_decimal value_1 = {{10, 0, 0, 0}};
  s21_decimal value_2 = {{20, 0, 0, 0}};
  set_sign(&value_1, minus);
  set_scale(&value_2, 5);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{1999990, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_positive_float_negative_int) {
  s21_decimal value_1 = {{10, 0, 0, 0}};
  s21_decimal value_2 = {{20, 0, 0, 0}};
  set_sign(&value_2, minus);
  set_scale(&value_1, 5);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{999980, 0, 0, 0}};
  set_scale(&expected, 5);
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_positive_and_negative) {
  s21_decimal value_1 = {{10, 0, 0, 0}};
  s21_decimal value_2 = {{20, 0, 0, 0}};
  set_sign(&value_2, minus);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{10, 0, 0, 0x80000000}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_negative_and_positive) {
  s21_decimal value_1 = {{10, 0, 0, 0}};
  s21_decimal value_2 = {{20, 0, 0, 0}};
  set_sign(&value_1, minus);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{10, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_overflow) {
  s21_decimal value_1 = {{4294967295, 4294967295, 4294967295, 0}};
  s21_decimal value_2 = {{1, 0, 0, 0}};
  s21_decimal expected = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 1);
}
END_TEST

START_TEST(add_overflow_two) {
  s21_decimal value_1 = {{1, 0, 0, 0}};
  s21_decimal value_2 = {{4294967295, 4294967295, 4294967295, 0}};
  s21_decimal expected = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 1);
}
END_TEST

START_TEST(add_overflow_three) {
  s21_decimal value_1 = {{4294967295, 4294967295, 4294967295, 0}};
  s21_decimal value_2 = {{4294967295, 4294967295, 4294967295, 0}};
  s21_decimal expected = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 1);
}
END_TEST

START_TEST(add_overflow_negative) {
  s21_decimal value_1 = {{4294967295, 4294967295, 4294967295, 0}};
  s21_decimal value_2 = {{1, 0, 0, 0}};
  set_sign(&value_1, minus);
  set_sign(&value_2, minus);
  s21_decimal expected = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 1);
}
END_TEST

START_TEST(add_overflow_negative_two) {
  s21_decimal value_1 = {{1, 0, 0, 0}};
  s21_decimal value_2 = {{4294967295, 4294967295, 4294967295, 0}};
  set_sign(&value_1, minus);
  set_sign(&value_2, minus);
  s21_decimal expected = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 1);
}
END_TEST

START_TEST(add_overflow_negative_three) {
  s21_decimal value_1 = {{4294967295, 4294967295, 4294967295, 0}};
  s21_decimal value_2 = {{4294967295, 4294967295, 4294967295, 0}};
  set_sign(&value_1, minus);
  set_sign(&value_2, minus);
  s21_decimal expected = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 1);
}
END_TEST

START_TEST(add_positive_numbers_zero) {
  s21_decimal value_1 = {{0, 0, 0, 0}};
  s21_decimal value_2 = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{0, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_positive_and_negative_zero) {
  s21_decimal value_1 = {{0, 0, 0, 0}};
  s21_decimal value_2 = {{0, 0, 0, 0}};
  set_sign(&value_2, minus);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{0, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_negative_and_positive_zero) {
  s21_decimal value_1 = {{0, 0, 0, 0}};
  s21_decimal value_2 = {{0, 0, 0, 0}};
  set_sign(&value_1, minus);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{0, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_negative_numbers_zero) {
  s21_decimal value_1 = {{0, 0, 0, 0}};
  s21_decimal value_2 = {{0, 0, 0, 0}};
  set_sign(&value_1, minus);
  set_sign(&value_2, minus);
  s21_decimal expected = {{0, 0, 0, 0}};
  s21_decimal result = {{0, 0, 0, 0}};
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_positive_numbers_float_big_scale) {
  s21_decimal value_1 = {{1, 0, 0, 0}};
  s21_decimal value_2 = {{2, 0, 0, 0}};
  set_scale(&value_1, 28);
  set_scale(&value_2, 27);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{12, 0, 0, 0}};
  set_scale(&expected, 27);
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

START_TEST(add_negative_numbers_float_big_scale) {
  s21_decimal value_1 = {{1, 0, 0, 0}};
  s21_decimal value_2 = {{2, 0, 0, 0}};
  set_sign(&value_1, minus);
  set_sign(&value_2, minus);
  set_scale(&value_1, 28);
  set_scale(&value_2, 27);
  s21_decimal result = {{0, 0, 0, 0}};
  s21_decimal expected = {{12, 0, 0, 0x80000000}};
  set_scale(&expected, 27);
  int return_code = s21_add(value_1, value_2, &result);

  ck_assert(s21_is_equal(result, expected) == 1);
  ck_assert(return_code == 0);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, set_sign_positive);
  tcase_add_test(tc1_1, set_sign_negative);
  tcase_add_test(tc1_1, get_sign_positive);
  tcase_add_test(tc1_1, get_sign_negative);
  tcase_add_test(tc1_1, set_bit_zero_false);
  tcase_add_test(tc1_1, set_bit_zero_true);
  tcase_add_test(tc1_1, set_bit_one_false);
  tcase_add_test(tc1_1, set_bit_one_true);
  tcase_add_test(tc1_1, set_bit_middle_false);
  tcase_add_test(tc1_1, set_bit_middle_true);
  tcase_add_test(tc1_1, set_bit_overflow_true);
  tcase_add_test(tc1_1, set_bit_overflow_false);
  tcase_add_test(tc1_1, add_positive_numbers);
  tcase_add_test(tc1_1, add_negative_numbers);
  tcase_add_test(tc1_1, add_positive_numbers_float);
  tcase_add_test(tc1_1, add_negative_numbers_float);
  tcase_add_test(tc1_1, add_positive_numbers_float_int);
  tcase_add_test(tc1_1, add_negative_float_positive_int);
  tcase_add_test(tc1_1, add_positive_int_negative_float);
  tcase_add_test(tc1_1, add_negative_int_positive_float);
  tcase_add_test(tc1_1, add_positive_float_negative_int);
  tcase_add_test(tc1_1, add_positive_and_negative);
  tcase_add_test(tc1_1, add_negative_and_positive);
  tcase_add_test(tc1_1, add_overflow);
  tcase_add_test(tc1_1, add_overflow_two);
  tcase_add_test(tc1_1, add_overflow_three);
  tcase_add_test(tc1_1, add_overflow_negative);
  tcase_add_test(tc1_1, add_overflow_negative_two);
  tcase_add_test(tc1_1, add_overflow_negative_three);
  tcase_add_test(tc1_1, add_positive_numbers_zero);
  tcase_add_test(tc1_1, add_positive_and_negative_zero);
  tcase_add_test(tc1_1, add_negative_and_positive_zero);
  tcase_add_test(tc1_1, add_negative_numbers_zero);
  tcase_add_test(tc1_1, add_positive_numbers_float_big_scale);
  tcase_add_test(tc1_1, add_negative_numbers_float_big_scale);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
